name: Trust Wallet SDK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang libboost-all-dev libgtest-dev protobuf-compiler libprotobuf-dev

    - name: Configure SDK
      run: >
        cmake -B build 
        -DBUILD_TESTS=OFF 
        -DCMAKE_C_COMPILER=clang 
        -DCMAKE_CXX_COMPILER=clang++ 
        -DProtobuf_USE_STATIC_LIBS=OFF
        -DTW_SDK_BUILD=ON

    - name: Compile SDK
      run: cmake --build build -j4
